version: '3'
services:

    # The Web Server
    web:
        build:
            context: ./
            dockerfile: ./docker/web.docker
        working_dir: /var/www
        volumes:
            - .:/var/www:rw
            - ./docker/dev/app/conf:/etc/nginx/conf.d:rw
            - ./env/app/log:/var/log/nginx:rw
        depends_on:
            - app
        ports:
            - 8000:80

    # The Application
    app:
        build:
            context: ./
            dockerfile: ./docker/app.docker
        working_dir: /var/www
        volumes:
            - ./:/var/www:rw
        depends_on:
            - database
            - redis
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    # The Que
    queue:
        build:
            context: ./
            dockerfile: ./docker/app.docker
        depends_on:
            - app
        volumes:
            - ./:/var/www:rw
        environment:
            APP_ENV: local
            CONTAINER_ROLE: queue

    # The Database
    database:
        image: mysql:5.7
        volumes:
            - ./env/database/mysql:/var/lib/mysql
            - ./env/database/dump:/docker-entrypoint-initdb.d
            - ./docker/database/conf:/etc/mysql/conf.d
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=app"
            - "MYSQL_USER=app_user"
            - "MYSQL_PASSWORD=app_pwd"
        ports:
            - "3306:3306"

    # redis
    redis:
        image: redis
        ports:
            - "6379:6379"

    # composer
    composer:
        image: composer/composer:2
        volumes:
            - ./:/var/www:rw
        working_dir: /var/www/
